import com.mxgraph.swing.mxGraphComponent;
import org.jgrapht.ext.JGraphXAdapter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class Main {
    private JPanel rootPanel;
    private JLabel textLabel;
    private JPanel graphPanel;
    private JButton testButton;

    private List<GraphData> dataList;
    private JGraphXAdapter graphXAdapter;
    private LSA lsa;

    public Main() {
        testButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
//                lsa.computeAll();
//                lsa.printAllTable();
                if (lsa.computeNext()) {
                    lsa.printTable();
                    graphPanel.removeAll();
                    drawPath(dataList, lsa.getPathTo(lsa.getCurrentNearest()));
                    graphPanel.revalidate();
                    graphPanel.repaint();
                }
            }
        });
    }

    public void drawPath(List<GraphData> graphDataList, List<String> path) {
        this.graphXAdapter = new GraphVisualization().getShortestPathGraphByPath(graphDataList, path);
        graphPanel.add(new mxGraphComponent(this.graphXAdapter));
    }

    public void drawGraph(List<GraphData> graphDataList) {
        this.graphXAdapter = new GraphVisualization().getNetworkGraph(graphDataList);
        graphPanel.add(new mxGraphComponent(this.graphXAdapter));
    }

    public static void main(String[] args) {
        String a = "A1";
        String b = "B2";
        String c = "C3";
        String d = "D4";
        String e = "E5";
        String f = "F6";


        List<GraphData> graphDataList = new ArrayList<>();
        graphDataList.add(new GraphData(a, b, 5));
        graphDataList.add(new GraphData(b, a, 5));

        graphDataList.add(new GraphData(a, c, 3));
        graphDataList.add(new GraphData(c, a, 3));

        graphDataList.add(new GraphData(a, d, 5));
        graphDataList.add(new GraphData(d, a, 5));

        graphDataList.add(new GraphData(c, b, 4));
        graphDataList.add(new GraphData(b, c, 4));

        graphDataList.add(new GraphData(c, d, 1));
        graphDataList.add(new GraphData(d, c, 1));

        graphDataList.add(new GraphData(b, f, 2));
        graphDataList.add(new GraphData(f, b, 2));

        graphDataList.add(new GraphData(b, e, 3));
        graphDataList.add(new GraphData(e, b, 3));

        graphDataList.add(new GraphData(d, e, 3));
        graphDataList.add(new GraphData(e, d, 3));

        JFrame frame = new JFrame("App");
        Main main = new Main();
        main.lsa = new LSA(graphDataList, a);
        main.drawGraph(graphDataList);
        main.dataList = graphDataList;
        frame.add(main.rootPanel);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        textLabel = new JLabel();
        textLabel.setText("Test");
        rootPanel.add(textLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        graphPanel = new JPanel();
        graphPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.add(graphPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        testButton = new JButton();
        testButton.setText("Button");
        rootPanel.add(testButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
